# Generated by Django 4.0.3 on 2022-04-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(default=0)),
                ('state', models.IntegerField(choices=[(0, 'unread'), (1, 'read')], default=0)),
                ('type', models.IntegerField(choices=[(0, 'diagnosis'), (1, 'manage'), (2, 'apply')], default=0)),
                ('content', models.TextField(null=True)),
                ('post_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Notificaitons',
                'ordering': ('post_time',),
            },
        ),
    ]
