# Generated by Django 4.0.3 on 2022-04-09 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='nid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='uid',
            new_name='target_user',
        ),
    ]
