# Generated by Django 4.0.3 on 2022-04-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_rename_nid_notification_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='state',
            field=models.CharField(choices=[(0, 'unread'), (1, 'read')], default='unread', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[(0, 'diagnosis'), (1, 'manage'), (2, 'apply')], default='diagnosis', max_length=100),
        ),
    ]
