# Generated by Django 4.0.3 on 2022-04-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notification_state_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='state',
            field=models.IntegerField(choices=[(0, 'unread'), (1, 'read')], default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.IntegerField(choices=[(0, 'diagnosis'), (1, 'manage'), (2, 'apply')], default=0),
        ),
    ]
