# Generated by Django 4.0.3 on 2022-04-09 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('notification', '0004_alter_notification_state_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='target_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
