# Generated by Django 4.0.2 on 2022-04-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_alter_notification_target_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='emergency',
            field=models.IntegerField(choices=[(0, 'not_emergency'), (1, 'emergency')], default=0),
        ),
    ]
