# Generated by Django 4.0.2 on 2022-04-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_notification_emergency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='emergency',
            field=models.IntegerField(choices=[(0, 'normal'), (1, 'warning'), (2, 'fatal')], default=0),
        ),
    ]
