# Generated by Django 4.0.2 on 2022-04-22 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0007_alter_notification_emergency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='emergency',
            new_name='level',
        ),
    ]
