# Generated by Django 4.0.3 on 2022-04-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=50)),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女'), (2, '未知')], default=2)),
                ('mobile', models.CharField(max_length=11, unique=True)),
                ('telephone', models.CharField(max_length=20, null=True)),
                ('mail', models.CharField(max_length=30, null=True)),
                ('quote', models.TextField(null=True)),
                ('avatar', models.CharField(max_length=255, null=True)),
                ('access', models.CharField(blank=True, max_length=20, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User',
                'db_table': 'Users',
                'ordering': ('created_time',),
            },
        ),
    ]
